### ISSUE TITLE
小程序mpvue框架安装sass依赖

### ISSUE THREAD

**Issue by ye63** [ye63/ye63.github.io#20]
```
npm i sass-loader node-sass --save
```

```css
<style scoped lang=scss>
.daily-page{
  .test-scss{
     color:red
  }
}
</style>
```
