### ISSUE TITLE
flex水平垂直居中

### ISSUE THREAD

**Issue by ye63** [ye63/ye63.github.io#96]
```css
.box {
	display: flex;
	align-items: center;/*垂直居中*/
	justify-content: center;/*水平居中*/
}
```
