### ISSUE TITLE
如何让pre标签自动换行？

### ISSUE THREAD

**Issue by ye63** [ye63/ye63.github.io#97]
pre标签会原样保留HTML内容的格式，可是如果宽度过大会把页面撑坏，这时候需要自动换行来帮忙：

```css
pre {
	white-space: pre-wrap;
	white-space: -moz-pre-wrap;
	white-space: -pre-wrap;
	white-space: -o-pre-wrap;
}

.parent pre {
	word-wrap: break-word;
	white-space: normal;
}
```
scss写法
```scss
.pre-container {
    word-wrap: break-word;
    white-space: normal;
    pre {
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
        white-space: -pre-wrap;
        white-space: -o-pre-wrap;
        word-wrap: break-word;
    }
}
```
